name: Update gist with Steam Playtime

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0"  # 每天 UTC 00:00 运行
    #- cron: "*/10 * * * *"  # 调试用，正式使用改为 "0 0 * * *"
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 74509e3972291ac0a5f8a6fda639e607
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
           
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod  # Go 模块依赖缓存目录
            ~/.cache/go-build # Go 构建缓存目录
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Install dependencies
        run: go mod download
      
     # - name: Check out code into the Go module directory
     #   uses: actions/checkout@v2

      - name: Debug env variables
        run: |
            echo "STEAM_API_KEY: $STEAM_API_KEY"
            echo "GH_TOKEN: $GH_TOKEN"
            echo "STEAM_ID: $STEAM_ID"
      - name: Update-gist
        run:  go run ./cmd/box/main.go

